### ISSUE TITLE
Add information about default plugins

### ISSUE THREAD

**Issue by RobertoPrevato** [Neoteroi/mkdocs-plugins#1]
To not create confusion in readers who are configuring plugins for the first time, include information about default plugins:

```yaml
plugins:
  - search  # <--
  - neoteroi.mkdocsoad:
      use_pymdownx: true
```
