### ISSUE TITLE
Cards: Add a method of specifying a non-default image size 

### ISSUE THREAD

**Issue by jon-harper** [Neoteroi/mkdocs-plugins#28]
I'm using card grids both as a "big link button" and for an image gallery (along with glightbox).

I've basically used your stylesheet and hand-rolled the pages. In my own included CSS file I have an `nt-gallery` class, as well as `nt-gallery-image` and `nt-gallery-title` (no text class). I copied and then tweaked the settings from your own CSS file:

```css
.nt-card .nt-gallery-image {
    text-align: center;
    border-radius: 5px;
    background-position: center center;
    background-size: cover;
    background-repeat: no-repeat;
    min-height: 200px;
}

.nt-card .nt-gallery-image img {
    height:200px;
    margin-top:5px
}

.nt-card .nt-gallery-content {
    padding:.4rem
}

.nt-card .nt-gallery-title {
    text-align: center;
    /* font-weight: 400; */
    font-size: 0.9em;
    font-weight: 700;
    margin:4px 0 8px 0;
    line-height:20px
}
```

I'm using both side-by-side with good success:

![image](https://user-images.githubusercontent.com/11852387/205093142-7d40b37b-aff9-4cf7-ae7d-7a6c3b93185c.png)

You can see on top cards using `nt-card-*` and below the modified gallery version.

## Proposal

I propose to add a variable to pass to the `card()` call with the desired image height. From there it could calculate `min-height` values to apply as well.

An alternative would be a `card_gallery()` function that applies slightly modified styles, as I have done.

By the way, thank you for this project. It's done wonders for my documentation.
