### ISSUE TITLE
[Contribs plugin] Any support for excluding folders 

### ISSUE THREAD

**Issue by jravinder** [Neoteroi/mkdocs-plugins#33]
Thanks for the plugins!!
Are there any plans to exclude folders for obtaining contributor information?

**Comment by RobertoPrevato** [comment]
Hi @jravinder 
Sorry for the late response. I like your idea! 
Do you mean something like:

```yaml
  - neoteroi.contribs:
      exclude:
        - "example/*.md"
        - "some-page.md"

```

I plan to make some changes to the library soon, I might include this feature.

**Comment by RobertoPrevato** [comment]
Hi @jravinder 
This feature is now available. It took me a long time because I focused more on my web framework lately, and some other libraries.

You can exclude folders or files this way:

```yaml
  - neoteroi.contribs:
      exclude:
        - "index.md"
```

Glob patterns are supported, like:

```yaml
  - neoteroi.contribs:
      exclude:
        - "index.md"
        - "folder/some*"
```

Leaving this document as I still need to document this feature.
