### ISSUE TITLE
Links in Cards

### ISSUE THREAD

**Issue by carried-away** [Neoteroi/mkdocs-plugins#53]
Hello,

Using your example in https://www.neoteroi.dev/mkdocs-plugins/cards/#options, I'm not able to get the cards to generate the link.

Here is what I have in the markdown file

``` yaml
- title: Zeus
  content: |
    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor
    incididunt ut labore et dolore magna aliqua.
  image: ./img/icons/001-zeus.png
  url: https://en.wikipedia.org/wiki/Zeus
```

i know i do not have the image, so i expect that to 404, but when i hover over the card, it displays the path to the image. When clicked, it tries to open the image in a preview as opposed to the wikipedia link. I even tried using an image i do have and tried with the image property removed altogether.

When I check dev options, i do see the 'a href' element wrapping the nt-card class, but it doesn't manifest on the page.
