### ISSUE TITLE
[Question] relative URL for cards?

### ISSUE THREAD

**Issue by YozoraXCII** [Neoteroi/mkdocs-plugins#55]
This is a question rather than an issue, my apologies.

I'm trying to set up Cards, but I want the url to point to a local location (i.e. "myfile.html") rather than a hard-coded URL - is this possible? I can't seem to figure it out.

**Comment by YozoraXCII** [comment]
Solved it

**Comment by helmlingp** [comment]
> Solved it

@YozoraXCII how did you solve it?

**Comment by YozoraXCII** [comment]
> > Solved it
> 
> @YozoraXCII how did you solve it?

```yaml
- title: TMDb Icon
  content: This is a test
  image: ../assets/icons/tmdb.png
  url: "../tmdb"
  ```
