### ISSUE TITLE
[OpenAPI, Styles] Missing CSS styling for OpenAPI Docs?

### ISSUE THREAD

**Issue by Jadarma** [Neoteroi/mkdocs-plugins#59]
I was trying to set up a demo sample, everything works as intended, except the styling does not seem to match the images in the [documentation](https://www.neoteroi.dev/mkdocs-plugins/web/oad/).

I did download the CSS from [Release 1.0.4](https://github.com/Neoteroi/mkdocs-plugins/releases/tag/v1.0.4) _(and seems like 1.0.5 doesn't provide it?)_, and I am sure it is correctly set up because other plugins like cards work.

The main thing I noticed missing is the coloring of the HTTP methods, like how POST is colored blue in the example result. Inspecting the HTML, I see the elements do have a `http-post` class and everything, but there is no mention of it anywhere in the CSS file. I then looked at the source files in this repo, and there is no file for the OpenAPI docs, only the other plugins.

Is the CSS for this plugin available somewhere separately, or am I missing something? Thank you!

For reference, my `mkdocs.yml`:
```yml
site_name: My Docs
theme:
  name: material

plugins:
  - search
  - neoteroi.mkdocsoad:
      use_pymdownx: true

markdown_extensions:
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - neoteroi.cards

extra_css:
  - css/mkdocsoad.css
```
And a screenshot:
![image](https://github.com/Neoteroi/mkdocs-plugins/assets/9288322/47a38ee0-d996-48c5-ae95-b5a81169e116)
