### ISSUE TITLE
mkdocsoad: Failed to read source

### ISSUE THREAD

**Issue by LuisHPorras** [Neoteroi/mkdocs-plugins#65]
First of all, thanks a lot for your work, looks great and I'm willing to be able to test it and make use of it!

## Problem
I'm just trying to make use of the plugin but I'm not able to do it. I'm following the [docs](https://www.neoteroi.dev/mkdocs-plugins/web/oad/), install the dependencies, configure the `mkdocs.yml`:

```yaml
# ... some config

nav:
    - Inicio: index.md
    - 'Hoja de ruta': roadmap.md
    - Cliente: 
        - Inicio: client/index.md
    - Servidor: 
        - Inicio: server/index.md
        - API: server/api.md
    - 'Meta-documentación': metadocs.md

# ... more config

plugins:
    - search
    - git-revision-date
    - neoteroi.mkdocsoad:
        use_pymdownx: true

markdown_extensions:
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.tabbed:
        alternate_style: true
    - toc:
          permalink: true
```
Create the new entry in the docs `./server/api.md`:
```md

# __API__

[OAD(./openapi.yaml)]

```
Provide the openapi generated json file in the samse directory. And I get the following error when launching `mkdocs serve`:

```bash
ValueError: Invalid source: it must be either a path to .json or a .yaml file, or a valid URL. 
```
I'm using [Swagger editor](https://editor.swagger.io/) to validate the openapi file and it doesn't contain errors. You can find the code at [PROECOS](https://framagit.org/amoved/hepe) **branch _19-documentation_**

I haven't found much information for troubleshooting in the docs, I'll be willing to PR with updated docs if we get to find the solution.

Cheers!
