### ISSUE TITLE
Could not render a timeline block. Please correct the input.

### ISSUE THREAD

**Issue by ZhangzrJerry** [Neoteroi/mkdocs-plugins#68]
I installed the plugin via pip and copied the .css file to the file system, and

```yml
extra_css:
  - stylesheets/index.css
  - stylesheets/blog.css
  - stylesheets/resume.css
  - stylesheets/academics.css
  - stylesheets/neoteroi.css

markdown_extensions:
  - attr_list
  - md_in_html
  - neoteroi.projects
  - neoteroi.timeline
```

```yaml
::timeline::

- content: First implementation.
  icon: ':material-rocket-launch-outline:'
  sub_title: 2022-Q1
  title: Launch

::/timeline::
```

```markdown
[timeline(./docs/gantt/timeline.yaml)]
```

but it throws 
![image](https://github.com/user-attachments/assets/83b4f032-90c9-4989-9323-b72466e06254)
